theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  breadcrumb:
    position: after-hero
  summary:
    position: hero
  logo:
    footer: "/assets/images/logo-blanc.svg"